WIP Add .travis.yml
ufora/ufora pull request #296
Opened 2017-03-25 18:54 UTC by gliptak

Signed-off-by: Gábor Lipták <gliptak@gmail.com>

I added a TravisCI build file. The build runs longer than ~50 minutes hence it times out.

https://travis-ci.org/gliptak/ufora/builds/214856415

I'm not sure that the WAF build runs in parallel ...

2017-04-13 18:09 UTC, atzannes requested changes
Sorry for the delay in reviewing, the project is a bit dormant right now. 

The addition of the .travis.yml file seems fine, the other changes don't seem desirable

2017-04-13 18:09 UTC, atzannes commented on make.sh
This might be the reason why the build times out -vv produces *a lot* of output, you may want to revert back this change

2017-04-13 18:09 UTC, atzannes commented on wscript
> +    bld.jobs = 4
What's the difference between POST_LAZY and POST_AT_ONCE? 
I don't think you want to restrict bld.jobs to 4 (assuming it acts like the -j option of make to controll how many concurrent processes are allowed). During local builds, ./waf uses as many processes as my cores by default, so I think you may want to rever this change as well.

2017-04-13 19:18 UTC, gliptak commented
Thank you for the review. I left the debug flags with the PR to help somebody with better understanding WAF to help with shortening the build time.
With or without the debug switches, build currently runs longer than ~50 minutes, so Travis times out ...

2017-04-13 19:22 UTC, atzannes commented
The build takes a long time. On my machine with 6-way parallelism it took close to 25 minutes, so unless you figure out how to make it run in parallel on travis, it is not going to complete in 50 minutes. Is that a travis limitation? Have you managed to build locally? Do you need me to point you to some docs for doing that?

2017-04-13 19:30 UTC, gliptak commented
My local build was also very long, hence I was hoping to take advantage of Travis :)
It seems that WAF runs a separate GCC process for each file, instead of compiling sets of them.

2017-04-13 19:36 UTC, atzannes commented
Because the build takes long, we want to optimize the dev-cycle (modify-compile-test), therefore we want to compile as few files as possible when we recompile, so compiling sets of files is not desirable. Moreover, compiling files separately also gives you tons of parallelism. If you manage to make parallelism work on travis you can get build time to be *very* short by throwing processors at it.

2017-04-13 22:36 UTC, gliptak commented
So could a CI version of the https://github.com/ufora/ufora/tree/master/build files be created (compiling sets of files, as incremental compilation is of no value ...)? Thanks

2017-04-22 14:11 UTC, gliptak commented
Pointers?

2017-05-18 20:10 UTC, closed without merging